#!/usr/bin/env python
# -*-coding=utf-8 -*-

#生成秘钥
from Crypto import Random
from Crypto.PublicKey import RSA

random_generator = Random.new().read
rsa = RSA.generate(1024, random_generator)

private_pem = rsa.exportKey()

with open('private.pem','wb') as f:
    f.write(private_pem)

public_pem = rsa.publickey().exportKey()

with open('public.pem','wb') as f:
    f.write(public_pem)
    
    
#加解密数据
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_v1_5 as Cipher_pkcs1_v1_5

import base64

message = 'abc'
with open('public.pem','r') as f:
    key = f.read()

    rsakey = RSA.importKey(key)
    cipher = Cipher_pkcs1_v1_5.new(rsakey)
    cipher_text = base64.b64encode(cipher.encrypt(message.encode(encoding="utf-8")))
    print cipher_text

with open('private.pem','r') as f:
    key = f.read()
    rsakey = RSA.importKey(key)
    cipher = Cipher_pkcs1_v1_5.new(rsakey)
    text = cipher.decrypt(base64.b64decode(cipher_text), "ERROR")
    print text
