#!/usr/bin/env python
# -*-coding=utf-8 -*-

import socket
import sys

host = "0.0.0.0"
port = 8081

sl = socket.socket()
sl.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
sl.bind((host,port))
sl.listen(5)

while True:
    conn, addr = sl.accept()
    print "connect:" ,addr
    cdata = conn.recv(2048)
    src = cdata.split(" ")[1]
    print src
    cc = cdata.split('\r\n\r\n')
    print cc[1]
    if src == "/long":
        content = "HTTP/1.1 200 ok\r\nContent-Type: application/json\r\n\r\n"
        content = content + '{"res":200,"msg":"ok"}'
        conn.sendall(content)
    else:
        conn.sendall('not allow')
    conn.close()
    sys.exit()
